version: '3'
services:
  app:
    container_name: nhumapp_app
    command: yarn start
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - 19000:19000
      - 19001:19001
    volumes:
     - .:/usr/src/app
    working_dir: /usr/src/app